name: social_share
description: Wide variety of sharing options you'll need to share directly to certain well-known apps.
version: 2.2.1
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shekarmudaliyar.social_share
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin
